### ISSUE TITLE
Increase praise text length to 500 characters

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#1080]
Related to user question:

_I have a question, we've been having some issues with the characters limit that the praise bot has. Is there a way to bring it up to 500 characters?

People have been writing praise a little bit longer than 280 (which is the current limit) and when they send it the bot fails to record it and the text that they wrote gets lost
I can't seem to find a way to change this in the dashboard settings_

**Comment by kristoferlund** [comment]
Yes, this is something we should consider. Don't know what the right length might be though.

**Comment by kkatusic** [comment]
I don't know, we don't write autobiography in the Praise :) We didn't ask him what he wanted to write and miss space :(

**Comment by laurenluz** [comment]
I agree that 400 or 500 characters would be enough. The Giveth community is very experience in using praise and crafting detailed & clear messages. Many of us are getting "cut off: with 280 characters.

if you insist on keeping in very short like 280 char, you should build in some kind of character counter that doesn't let you send the message unless it is under the limits. very bad UX to write a careful, thoughtful praise and then just have it be deleted because praisebot says it's too long.

**Comment by kkatusic** [comment]
What is Discord limit?

**Comment by kristoferlund** [comment]
@laurenluz Ok, great, let's make it 500 then.

**Comment by kkatusic** [comment]
@kristoferlund check last commit, thx
