### ISSUE TITLE
Praise as a Service

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#709]
High level specs available on Notion: https://www.notion.so/giveth/Praise-as-a-service-31428d21d36342eb805fd71e6955a472

## Use case

Deploy Praise easily with just a few clicks starting on the givepraise.xyz webpage.

## Main question

How do we provide a hosted Praise service for 500 communities that is fast, cheap and allows communities to setup by themselves in 5 minutes?

## User facing requirements / ideas

- A glossy button on the givepraise.xyz:  "Deploy Praise"
- Redirects you to the setup web: `setup.givepraise.xyz`
- A visual setup wizard with as few steps as possible
- On completion of wizard, a setup service does some magic in the background deploying your instance
- Once setup service is done, user is presented with a link to invite bot to Discord

## Backend requirements / ideas

- All communities use the same instance of the Praise Discord bot. The bot needs to be upgraded to handle traffic from different communities.
- All communities gets served the same package for the frontend (Praise Dashboard). 
- Every community gets its own subdomain on `[community].givepraise.xyz`
- All communities share a number of API instances. Horizontal scaling (adding more API instances) should be possible.

**Comment by Vyvy-vi** [comment]
I was thinking about something like this:
- the bot isn't accessing the api
- instead of running multiple bots, we run one discord bot that is sharded into multiple instances, which saves $ in the long run.
- instead of one api one droplet one community, we run one api for all the communites combined, which runs on some droplets sharing the load (*this would need a major db re-write, but would serve better for saas purposes + create a profit margin for us)
- instead of multiple dbs, one db that can work in a distributed / decentralised manner managing all the data. The mongodb atlas cloud service could work well enough if we scale up when needed. (Though, maybe some other service would be better suited? not sure? I think matty suggested something about this related to switching to a different db...)

*this would need a lot of work, though I think even taking parts of this system can be beneficial, like - single bot for all servers. This reduces confusion and would allow us to take advantage of the fact that the Application Commands (Slash commands) can work serverless

<img width="1283" alt="Screenshot_2022-12-28_at_7 08 10_PM" src="https://user-images.githubusercontent.com/62864373/209823007-e660e59c-9816-441b-a524-6bd40c65244c.png">

**Comment by mhmdksh** [comment]
This should be an epic, as a lot of things need to be done under this umbrella

**Comment by kristoferlund** [comment]
> This should be an epic, as a lot of things need to be done under this umbrella

It is an epic.. :)

**Comment by mhmdksh** [comment]
> > This should be an epic, as a lot of things need to be done under this umbrella
> 
> It is an epic.. :)

Oh man, how did I not see that :`)
