### ISSUE TITLE
Configure Caddy to handle new multi community setup

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#911]
What we need is this for the staging server and later for the production server to handle this:

Incoming traffic:
```
one.dev.givepraise.xyz
two.dev.givepraise.xyz
customdomain.com
```

- All that traffic gets served the same frontend, backend calls get routed to the same API.
- No changes to API needed, API looks at host header to determine community
- We don't need to rely on Caddy like we have if there is some better/simpler way to solve it
- We need to be able to easily add to the config of the reverse proxy / DNS though
  - Setting up a new Praise community on `*.dev.givepraise.xyz` should require no change (wildcard config alreday in place)
  - Setting up a Community with custom domain requires DNS change (community does that) and config change of reverse proxy. This is change is not a core feature of the Praise API but can rather be done in some external script (and later admin dashboard)

**Comment by mhmdksh** [comment]
Thanks for creating the issue @kristoferlund. So as I understood, the api will now handle what is the subdomain, correct? Also thing to discuss, we might also need the database name to be the same as the subdomain AAA record, so that it is also pointed to it automatically. @mohammadranjbarz any Idea?

So I think there might be several ways to do this.
1- Using something like this on an nginx frontend
`
server {
  server_name ~^(.*)\.example\.com$ ;
  root www/pub/$1;
}
`
2- Using a wildcard subdomain with a Kubernetes Implementation:
`
spec:
  rules:
  - host: '*. dev.givepraise.xyz'
    http:
      paths:
      - backend:
          serviceName: praise
          servicePort: 8080
        path: /(.*)
        pathType: ImplementationSpecific
`

**Comment by kristoferlund** [comment]
Yes, the community database name should be based on the domain name of the community. Only difference: dots get replaced by hyphens, like this:

Community domain name: `one.dev.givepraise.xyz`
Community database name: `one-dev-givepraise-xyz`

**Comment by mhmdksh** [comment]
What do you mean by domains we control? We will be controlling *.dev.givepraise.xyz after all, correct??

> @mhmdksh What you propose there solves the default domains that we control but not the custom domain scenario.

**Comment by mhmdksh** [comment]
@kristoferlund 
I have setup the right config for domain mappings, you can check them in Cloudflare here:

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/52987806/231691181-13f45fbb-f7ce-4986-99f7-f2cecae718e0.png">

And you can test this as below:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/52987806/231691074-4a735a2b-06ee-45c6-9f1d-1b00bab14e11.png">

**Comment by kristoferlund** [comment]
@mhmdksh See the first message again please. We also need to support custom domains.

**Comment by mhmdksh** [comment]
Ok so after following this issue and putting in some time into researching how to solve this problem. I came up with the best solution that I could find. Here it goes:

1. We need to update the Caddy config to be able to manage and handle more domains, in 2 ways
  a- When we have a Custom Domain (Any Domain)
  b- When we have a WildCard Subdomain (*.dev.givepraise.xyz)

2. We need to update our Frontend Dockerfile to build a Caddy image that is able to comprehend the new changes and is able to communicate with outside DNS Provider using API_KEYs (Check further below)

**Caddyfile Update:**
```
// Creating the on-demand TLS config, which is pointing to our domain verification endpoint
{
    email admin@givepraise.xyz
    admin off
    on_demand_tls {
        ask https://api.givepraise.xyz/check-domain
        interval 2m
        burst 5
    }
}

// The Server Configs for the on-demand TLS Configs
// This will check the endpoint that we created in the earlier step to see if the RESPONSE was 200 OK 
// and will create the certificate for the specified domaine from the endpoint
:443 {
    tls {
        on_demand
    }
    log {
        output file /var/log/caddy/access.log {
            format '{remote} - [{when}] "{method} {uri} {proto}" {status} {size}'
        }
    }
    handle /api* {
        reverse_proxy api:{$API_PORT}
    }

    handle /uploads* {
        reverse_proxy api:{$API_PORT}
    }
    handle {
        root * /var/www/praise
        try_files {path} /index.html
        encode zstd gzip
        file_server
    }
}

// This is the configuration for the wildcard Certificate that will be used for the Wildcard Subdomains
*.dev.givepraise.xyz {
    tls {
        dns cloudflare {env.CLOUDFLARE_API_TOKEN}
        resolvers 1.1.1.1
    }
    log {
        output file /var/log/caddy/access.log {
            format '{remote} - [{when}] "{method} {uri} {proto}" {status} {size}'
        }
    }
    handle /api* {
        reverse_proxy api:{$API_PORT}
    }

    handle /uploads* {
        reverse_proxy api:{$API_PORT}
    }
    handle {
        root * /var/www/praise
        try_files {path} /index.html
        encode zstd gzip
        file_server
    }
}
```
As you can see, in the first configuration snippet, we are building the tls-on-demand config, which should communicate with an endpoint that we should create (https://api.givepraise.xyz/check-domain). This endpoint should have access to the Custom Domains registered under our Praise DB. And this is how it should work:

The endpoint (https://api.givepraise.xyz/check-domain) shall receive a GET query from the frontend (The Caddy Server), with a query string of ?domain= containing the value of the domain name, in which Caddy will be checking if the domain is available or not. If it is available it should return a 200 message and only then Caddy is able to proceed with requesting the certificate for that Domain

More Info here:
- https://caddyserver.com/docs/automatic-https#on-demand-tls
- https://caddyserver.com/docs/caddyfile/options#on-demand-tls

As for the second configuration snippet, we will be specifying our DNS provider for our wildcard certificate setup. Since by default Caddy will use the Let’s Encrypt HTTP-01 challenge type which requires port 80 to be open up to your server. Unfortunately, this is not a supported challenge type for wildcard certificates. To generate a wildcard certificate we will need to use the DNS-01 challenge type which requires using a [supported DNS provider](https://community.letsencrypt.org/t/dns-providers-who-easily-integrate-with-lets-encrypt-dns-validation/86438).

To achieve this, we need to rebuild the frontend image as follow:

**Dockerfile Update:**
```
FROM node:18.15 as builder

# Create app directory
WORKDIR /usr/src/

# Copy workspace config
COPY ./package*.json .
COPY ./.eslintrc.js .
COPY ./.yarnrc.yml .
COPY ./yarn.lock .
COPY ./.yarn ./.yarn

# Copy packages
COPY ./packages/api-types ./packages/api-types
COPY ./packages/frontend ./packages/frontend

# Install dependencies
RUN corepack enable
RUN yarn

# Build the app
RUN yarn workspace frontend build

# Serve the app with Caddy
FROM caddy:builder AS cbuilder
RUN caddy-builder github.com/caddy-dns/cloudflare
FROM caddy:2.6.4-alpine
COPY --from=cbuilder /usr/bin/caddy /usr/bin/caddy

COPY ./packages/frontend/Caddyfile /etc/caddy/Caddyfile
COPY --from=builder /usr/src/packages/frontend/build /var/www/praise
```

As you can see, we are adding another build snippet under the Caddy, where it will use Cloudflares DNS plugin for Caddy, that is officially developed by them.
More info here:
- https://caddy.community/t/how-to-guide-caddy-v2-cloudflare-dns-01-via-docker/8007
- https://github.com/caddy-dns/cloudflare

I can add PRs for the above configs. But I would appreciate your feedback @kristoferlund
Also @mohammadranjbarz I would appreciate your feedback about the domain checking endpoint mentioned above.

**Comment by kristoferlund** [comment]
Solution above looks cool @mhmdksh but also rather complex. Couldn't we also go with what you initially suggested?

```
DOMAIN1, DOMAIN2, DOMAIN3 {
  reverse_proxy localhost:8088
}
```

Then we don't need to care about wildcard domains or anything. The only thing we need to pay attention to is that we update the Caddy config when we add a new community (or change). And then tell Caddy to gracefully reload.

Would this work in our example setup?
```
one.dev.givepraise.xyz, two.dev.givepraise.xyz, customdomain.com {
  reverse_proxy localhost:8088
}
```

**Comment by mhmdksh** [comment]
> Solution above looks cool @mhmdksh but also rather complex. Couldn't we also go with what you initially suggested?
> 
> ```
> DOMAIN1, DOMAIN2, DOMAIN3 {
>   reverse_proxy localhost:8088
> }
> ```
> 
> Then we don't need to care about wildcard domains or anything. The only thing we need to pay attention to is that we update the Caddy config when we add a new community (or change). And then tell Caddy to gracefully reload.
> 
> Would this work in our example setup?
> 
> ```
> one.dev.givepraise.xyz, two.dev.givepraise.xyz, customdomain.com {
>   reverse_proxy localhost:8088
> }
> ```
As this might work, but it won't be effective to configure it in this way when we want to have 1000 communities.
However, Caddy is now configured to be ready to take these connections, the mentioned changes have been implemented on the separate repo that we created here: https://github.com/givepraise/praise-staging/blob/main/packages/frontend/Caddyfile

This will satisfy the below requirements:

- Caddy can now server multiple subdomains as a with certificate used for wildcard subdomains, and is now configured on our staging server. This will accept connections to *.dev.givepraise.xyz as long as the community name info is in the DB
- Caddy can now serve multiple CUSTOM Domains as well, and this is also available when we created an endpoint in the api `/api/domain-check` that will check if the domain data exists in our database or not, and only then proceed with requesting the certificate. (An API change was of course required to achieve this)
**Note**: Caddy can only request the Custom DOMAIN Certificate in the following cases:

1. A community is found in the Database.
2. A CNAME Record pointing to --> `saas-backend-staging.givepraise.xyz` or an A record pointing to ---> `157.230.99.34`
